// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDTDJxoX28192K2d79kHl0g6nSO1T5nI',
    appId: '1:340210633452:web:2dfd77e34684bbc0f133c9',
    messagingSenderId: '340210633452',
    projectId: 'mission-37f67',
    authDomain: 'mission-37f67.firebaseapp.com',
    databaseURL: 'https://mission-37f67-default-rtdb.firebaseio.com',
    storageBucket: 'mission-37f67.firebasestorage.app',
    measurementId: 'G-F24BMV2T4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHUaBGhZwVioxhZTcmTfcAUDfAexDsHK4',
    appId: '1:340210633452:android:221919486e13588df133c9',
    messagingSenderId: '340210633452',
    projectId: 'mission-37f67',
    databaseURL: 'https://mission-37f67-default-rtdb.firebaseio.com',
    storageBucket: 'mission-37f67.firebasestorage.app',
  );
}
